trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  clean: true

- script: |
    echo "Creating Oqtane.Framework directory..."
    mkdir oqtane.framework
  displayName: 'Create Oqtane.Framework Directory'

- script: |
    echo "Cloning Oqtane Framework (master branch)..."
    git clone --depth 1 --branch master https://github.com/kioskFast/oqtane.framework.git oqtane.framework
  displayName: 'Clone Oqtane Framework (master branch)'

# Remove this delete if running a new setup for the first time
# Uncomment when doing an update to an existing install so it doesn't overwrite
# - script: |
#     echo "Deleting appsettings.json and appsettings.release.json..."
#     rm -f oqtane.framework/Oqtane.Server/appsettings.json
#     rm -f oqtane.framework/Oqtane.Server/appsettings.release.json
#  displayName: 'Delete AppSettings Files'
  
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'
  displayName: 'Install .NET SDK'

- script: |
    echo "Restoring dependencies for Oqtane..."
    cd oqtane.framework
    dotnet restore Oqtane.sln
  displayName: 'Restore Dependencies'

- script: |
    echo "Building Oqtane Server..."
    cd oqtane.framework
    dotnet build Oqtane.sln -c Release
  displayName: 'Build Oqtane'

- script: |
    echo "Publishing Oqtane Server..."
    cd oqtane.framework
    dotnet publish Oqtane.sln -c Release -o $(Build.ArtifactStagingDirectory)/oqtane
  displayName: 'Publish Oqtane'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '33ccb08b-86ec-4841-9327-6f308fb703d4'
    appName: 'RubbishFast'
    package: '$(Build.ArtifactStagingDirectory)/oqtane'
  displayName: 'Deploy Oqtane to Azure Web App'